# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:57
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
