# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:01
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0002_auto_20171116_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coord_1',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='building',
            name='coord_2',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='building',
            name='coord_3',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='building',
            name='coord_4',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='roadcoord',
            name='coordinate',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
