# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0003_auto_20171116_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadcoord',
            old_name='coordinate',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='roadcoord',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='mapsapps.Road'),
        ),
    ]
