# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0004_auto_20171116_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='roadcoord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='roadcoord',
            name='road',
        ),
        migrations.RemoveField(
            model_name='building',
            name='coord_1',
        ),
        migrations.RemoveField(
            model_name='building',
            name='coord_2',
        ),
        migrations.RemoveField(
            model_name='building',
            name='coord_3',
        ),
        migrations.RemoveField(
            model_name='building',
            name='coord_4',
        ),
        migrations.DeleteModel(
            name='RoadCoord',
        ),
        migrations.AddField(
            model_name='coord',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_coords', to='mapsapps.Building'),
        ),
        migrations.AddField(
            model_name='coord',
            name='road',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_coords', to='mapsapps.Road'),
        ),
        migrations.AlterUniqueTogether(
            name='coord',
            unique_together=set([('road', 'sequence'), ('building', 'sequence')]),
        ),
    ]
