# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0005_auto_20171116_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_coords', to='mapsapps.Building'),
        ),
        migrations.AlterField(
            model_name='coord',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='road_coords', to='mapsapps.Road'),
        ),
    ]
