# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsapps', '0006_auto_20171116_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='sequence',
            field=models.IntegerField(blank=True),
        ),
    ]
